### ISSUE TITLE
[BUG]当下载量正好为100g时（靠魔力兑换），减少下载量的兑换按钮直接消失

### ISSUE THREAD

**Issue by SwissRollC** [HDDolby/PublicDolby#2]
**问题描述**
下载量低于100g时，减少下载量处会正常显示"下载量已很低"
当下载量正好为100g时（靠魔力兑换），减少下载量的兑换按钮直接消失，白色边框也缺了一块

**复现步骤（此步骤很关键，能帮助开发快速定位并解决，请详细描述！）**
当下载量为0时先兑换增加100g下载，再准备兑换减少100g下载时就出现了
当下载量为200g，可以兑换一次下载量减少，再想兑换时也会出现

**期待的行为**
可以减为0或当下载量低于一定数目时（>200g）也显示"下载量已很低"

**截图**

**桌面端：**
win edge

**Comment by DolbyCoder** [comment]
已修復，缺失了正好等於100G的判斷
