### ISSUE TITLE
[BUG]短讯箱的bug

### ISSUE THREAD

**Issue by QRQF001** [HDDolby/PublicDolby#3]
**问题描述**
下家注册后系统会发送站内信提醒，短讯箱随着时间推移越来越多了
为方便管理短讯箱，在 短讯箱管理 功能处添加了额外的短讯箱
其他站点（图为UBits）可以这样做并且能正常使用短讯箱
杜比这样操作后，会导致收件箱、发件箱、添加的额外收件箱 均不显示任何短讯，能收到短讯，但看不了
已使用电脑和手机浏览器验证，确实是网站bug

**Comment by QRQF001** [comment]
复现步骤
![【2024-06-08 00-34-12】](https://github.com/HDDolby/PublicDolby/assets/62094806/0756d626-4ab9-4f88-a1a8-89def28dc3b9)

![【2024-06-08 12-21-41】](https://github.com/HDDolby/PublicDolby/assets/62094806/6d5a21a4-f2c5-4074-a1e9-f0abffe326fb)

**Comment by DolbyCoder** [comment]
已修復
