### ISSUE TITLE
[BUG] 通过修改排名链接参数可获取大量用户信息

### ISSUE THREAD

**Issue by ljweixiang** [HDDolby/PublicDolby#7]
https://www.hddolby.com/keeptop.php?ord=osize&limit=100

三周年庆典活动的保种排名链接中，可通过更改limit参数获取大量用户信息

**Comment by DolbyCoder** [comment]
limit就是限制的条数，修改数量可以显示更多，请问这个问题的点在哪？需要我们做什么？

**Comment by ljweixiang** [comment]
我的理解是，普通排行榜都会限制更改limit数字，一旦更改跳回首页，这样只有排行榜上的用户会被看到，保护了其他用户的信息。但在这个链接里我可以自由的修改limit参数，甚至可以获取到全站的用户，当然我也不知道这样算不算是个问题哈。
from 阿里邮箱 iPhone------------------------------------------------------------------
***@***.***>
日　期：2024年06月12日 14:38:01
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [HDDolby/PublicDolby] [BUG] 通过修改排名链接参数可获取大量用户信息 (Issue #7)

limit就是限制的条数，修改数量可以显示更多，请问这个问题的点在哪？需要我们做什么？

**Comment by DolbyCoder** [comment]
> 我的理解是，普通排行榜都会限制更改limit数字，一旦更改跳回首页，这样只有排行榜上的用户会被看到，保护了其他用户的信息。但在这个链接里我可以自由的修改limit参数，甚至可以获取到全站的用户，当然我也不知道这样算不算是个问题哈。 from 阿里邮箱 iPhone------------------------------------------------------------------ ***@***.***> 日　期：2024年06月12日 14:38:01 ***@***.***> ***@***.***>; ***@***.***> 主　题：Re: [HDDolby/PublicDolby] [BUG] 通过修改排名链接参数可获取大量用户信息 (Issue #7) limit就是限制的条数，修改数量可以显示更多，请问这个问题的点在哪？需要我们做什么？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

沒有問題，如果你不想你的數據被人看到，請在控制面板-安全設置 關閉 《数据参与排行榜》

**Comment by DolbyCoder** [comment]
稍微动了下，目前限制250条
